from BaseClasses import ItemClassification, Location



class TECLocation(Location):
    game = "Tetris Effect: Connected"




# I separated these in groups to make location creation straight forward. Should probably do the same with items honestly
#                                          ID
base_locations = {
    'The Deep Stage Cleared':              10,
    'Pharaoh\'s Code Stage Cleared':       11,
    'Karma Wheel Stage Cleared':           12,
    'Jellyfish Chorus Stage Cleared':      13,
    'Da Vinci Stage Cleared':              14,
    'Prayer Circles Stage Cleared':        15,
    'Ritual Passion Stage Cleared':        16,
    'Deserted Stage Cleared':              17,
    'Dolphin Surf Stage Cleared':          18,
    'Downtown Jazz Stage Cleared':         19,
    'Spirit Canyon Stage Cleared':         10,
    'Jewel Veil Stage Cleared':            11,
    'Forest Dawn Stage Cleared':           12,
    'Kaleidoscope Stage Cleared':          13,
    'Turtle Dreams Stage Cleared':         14,
    'Celebration Stage Cleared':           15,
    'Sunset Breeze Stage Cleared':         16,
    'Aurora Peak Stage Cleared':           17,
    'Zen Blossoms Stage Cleared':          18,
    'Ying & Yang Stage Cleared':           19,
    'Hula Soul Stage Cleared':             20,
    'Starfall Stage Cleared':              21,
    'Balloon High Stage Cleared':          22,
    'Mermaid Cove Stage Cleared':          23,
    'Orbit Stage Cleared':                 24,
    'Stratosphere Stage Cleared':          25,
    'Metamorphosis Stage Cleared':         26
}

effect_mode_locations = {
    'Marathon Mode Cleared':              30,
    'Zone Marathon Mode Cleared':         31,
    'Ultra Mode Cleared':                 32,
    'Sprint Mode Cleared':                33,
    'Master Mode Cleared':                34,
    'Classic Score Attack Mode Cleared':  35,
    'Chill Marathon Mode Cleared':        36,
    'Quick Play Mode Cleared':            37,
    'Playlist (Sea) Mode Cleared':        38,
    'Playlist (Wind) Mode Cleared':       39,
    'Playlist (World) Mode Cleared':      40,
    'All Clear Mode Cleared':             41,
    'Combo Mode Cleared':                 42,
    'Target Mode Cleared':                43,
    'Countdown Mode Cleared':             44,
    'Purity Mode Cleared':                45,
    'Mystery Mode Cleared':               46,
}

misc_locations = {
    "Perform 10 T-spins":                   50, 
    "Perform 10 back-to-backs":             51, 
    "Perform 15 Tetris line clears":        52, 
    "Perform a 10 line combo":              53, 
    "Earn an all clear":                    54, 
    "Perform 4 consecutive back-to-backs":  55, 
    "Earn a T-spin triple":                 56, 
    "Earn an octotris":                     57, 
    "Earn a dodecatris":                    58, 
    "Earn a decahexatris":                  59, 
    "Earn a perfectris":                    60, 
    "Earn a ultimatris":                    61, 
    "Earn a kirbtris":                      62
}

zen_ranksanity_locations = {
    'Area 1: E Rank':                540,
    'Area 1: D Rank':                541,
    'Area 1: C Rank':                542,
    'Area 1: B Rank':                543,
    'Area 1: A Rank':                544,
    'Area 1: S Rank':                545,
    'Area 1: SS Rank':               546,
    'Area 2: E Rank':                550,
    'Area 2: D Rank':                551,
    'Area 2: C Rank':                552,
    'Area 2: B Rank':                553,
    'Area 2: A Rank':                554,
    'Area 2: S Rank':                555,
    'Area 2: SS Rank':               556,
    'Area 3: E Rank':                560,
    'Area 3: D Rank':                561,
    'Area 3: C Rank':                562,
    'Area 3: B Rank':                563,
    'Area 3: A Rank':                564,
    'Area 3: S Rank':                565,
    'Area 3: SS Rank':               566,
    'Area 3: X Rank':                560,
    'Area 4: E Rank':                570,
    'Area 4: D Rank':                571,
    'Area 4: C Rank':                572,
    'Area 4: B Rank':                573,
    'Area 4: A Rank':                574,
    'Area 4: S Rank':                575,
    'Area 4: SS Rank':               576,
    'Area 5: E Rank':                580,
    'Area 5: D Rank':                581,
    'Area 5: C Rank':                582,
    'Area 5: B Rank':                583,
    'Area 5: A Rank':                584,
    'Area 5: S Rank':                585,
    'Area 5: SS Rank':               586,
    'Area 6: E Rank':                590,
    'Area 6: D Rank':                591,
    'Area 6: C Rank':                592,
    'Area 6: B Rank':                593,
    'Area 6: A Rank':                594,
    'Area 6: S Rank':                595,
    'Area 6: SS Rank':               596,

    'The Deep: E Rank':              100,
    'The Deep: D Rank':              101,
    'The Deep: C Rank':              102,
    'The Deep: B Rank':              103,
    'The Deep: A Rank':              104,
    'The Deep: S Rank':              105,
    'The Deep: SS Rank':             106,
    'Pharaoh\'s Code: E Rank':       110,
    'Pharaoh\'s Code: D Rank':       111,
    'Pharaoh\'s Code: C Rank':       112,
    'Pharaoh\'s Code: B Rank':       113,
    'Pharaoh\'s Code: A Rank':       114,
    'Pharaoh\'s Code: S Rank':       115,
    'Pharaoh\'s Code: SS Rank':      116,
    'Karma Wheel: E Rank':           120,
    'Karma Wheel: D Rank':           121,
    'Karma Wheel: C Rank':           122,
    'Karma Wheel: B Rank':           123,
    'Karma Wheel: A Rank':           124,
    'Karma Wheel: S Rank':           125,
    'Karma Wheel: SS Rank':          126,
    'Jellyfish Chorus: E Rank':      130,
    'Jellyfish Chorus: D Rank':      131,
    'Jellyfish Chorus: C Rank':      132,
    'Jellyfish Chorus: B Rank':      133,
    'Jellyfish Chorus: A Rank':      134,
    'Jellyfish Chorus: S Rank':      135,
    'Jellyfish Chorus: SS Rank':     136,
    'Da Vinci: E Rank':              140,
    'Da Vinci: D Rank':              141,
    'Da Vinci: C Rank':              142,
    'Da Vinci: B Rank':              143,
    'Da Vinci: A Rank':              144,
    'Da Vinci: S Rank':              145,
    'Da Vinci: SS Rank':             146,
    'Prayer Circles: E Rank':        150,
    'Prayer Circles: D Rank':        151,
    'Prayer Circles: C Rank':        152,
    'Prayer Circles: B Rank':        153,
    'Prayer Circles: A Rank':        154,
    'Prayer Circles: S Rank':        155,
    'Prayer Circles: SS Rank':       156,
    'Ritual Passion: E Rank':        160,
    'Ritual Passion: D Rank':        161,
    'Ritual Passion: C Rank':        162,
    'Ritual Passion: B Rank':        163,
    'Ritual Passion: A Rank':        164,
    'Ritual Passion: S Rank':        165,
    'Ritual Passion: SS Rank':       166,
    'Deserted: E Rank':              170,
    'Deserted: D Rank':              171,
    'Deserted: C Rank':              172,
    'Deserted: B Rank':              173,
    'Deserted: A Rank':              174,
    'Deserted: S Rank':              175,
    'Deserted: SS Rank':             176,
    'Dolphin Surf: E Rank':          180,
    'Dolphin Surf: D Rank':          181,
    'Dolphin Surf: C Rank':          182,
    'Dolphin Surf: B Rank':          183,
    'Dolphin Surf: A Rank':          184,
    'Dolphin Surf: S Rank':          185,
    'Dolphin Surf: SS Rank':         186,
    'Downtown Jazz: E Rank':         190,
    'Downtown Jazz: D Rank':         191,
    'Downtown Jazz: C Rank':         192,
    'Downtown Jazz: B Rank':         193,
    'Downtown Jazz: A Rank':         194,
    'Downtown Jazz: S Rank':         195,
    'Downtown Jazz: SS Rank':        196,
    'Spirit Canyon: E Rank':         200,
    'Spirit Canyon: D Rank':         201,
    'Spirit Canyon: C Rank':         202,
    'Spirit Canyon: B Rank':         203,
    'Spirit Canyon: A Rank':         204,
    'Spirit Canyon: S Rank':         205,
    'Spirit Canyon: SS Rank':        206,
    'Jewel Veil: E Rank':            210,
    'Jewel Veil: D Rank':            211,
    'Jewel Veil: C Rank':            212,
    'Jewel Veil: B Rank':            213,
    'Jewel Veil: A Rank':            214,
    'Jewel Veil: S Rank':            215,
    'Jewel Veil: SS Rank':           216,
    'Forest Dawn: E Rank':           220,
    'Forest Dawn: D Rank':           221,
    'Forest Dawn: C Rank':           222,
    'Forest Dawn: B Rank':           223,
    'Forest Dawn: A Rank':           224,
    'Forest Dawn: S Rank':           225,
    'Forest Dawn: SS Rank':          226,
    'Kaleidoscope: E Rank':          230,
    'Kaleidoscope: D Rank':          231,
    'Kaleidoscope: C Rank':          232,
    'Kaleidoscope: B Rank':          233,
    'Kaleidoscope: A Rank':          234,
    'Kaleidoscope: S Rank':          235,
    'Kaleidoscope: SS Rank':         236,
    'Turtle Dreams: E Rank':         240,
    'Turtle Dreams: D Rank':         241,
    'Turtle Dreams: C Rank':         242,
    'Turtle Dreams: B Rank':         243,
    'Turtle Dreams: A Rank':         244,
    'Turtle Dreams: S Rank':         245,
    'Turtle Dreams: SS Rank':        246,
    'Celebration: E Rank':           250,
    'Celebration: D Rank':           251,
    'Celebration: C Rank':           252,
    'Celebration: B Rank':           253,
    'Celebration: A Rank':           254,
    'Celebration: S Rank':           255,
    'Celebration: SS Rank':          256,
    'Sunset Breeze: E Rank':         260,
    'Sunset Breeze: D Rank':         261,
    'Sunset Breeze: C Rank':         262,
    'Sunset Breeze: B Rank':         263,
    'Sunset Breeze: A Rank':         264,
    'Sunset Breeze: S Rank':         265,
    'Sunset Breeze: SS Rank':        266,
    'Aurora Peak: E Rank':           270,
    'Aurora Peak: D Rank':           271,
    'Aurora Peak: C Rank':           272,
    'Aurora Peak: B Rank':           273,
    'Aurora Peak: A Rank':           274,
    'Aurora Peak: S Rank':           275,
    'Aurora Peak: SS Rank':          276,
    'Zen Blossoms: E Rank':          280,
    'Zen Blossoms: D Rank':          281,
    'Zen Blossoms: C Rank':          282,
    'Zen Blossoms: B Rank':          283,
    'Zen Blossoms: A Rank':          284,
    'Zen Blossoms: S Rank':          285,
    'Zen Blossoms: SS Rank':         286,
    'Ying & Yang: E Rank':           290,
    'Ying & Yang: D Rank':           291,
    'Ying & Yang: C Rank':           292,
    'Ying & Yang: B Rank':           293,
    'Ying & Yang: A Rank':           294,
    'Ying & Yang: S Rank':           295,
    'Ying & Yang: SS Rank':          296,
    'Hula Soul: E Rank':             300,
    'Hula Soul: D Rank':             301,
    'Hula Soul: C Rank':             302,
    'Hula Soul: B Rank':             303,
    'Hula Soul: A Rank':             304,
    'Hula Soul: S Rank':             305,
    'Hula Soul: SS Rank':            306,
    'Starfall: E Rank':              310,
    'Starfall: D Rank':              311,
    'Starfall: C Rank':              312,
    'Starfall: B Rank':              313,
    'Starfall: A Rank':              314,
    'Starfall: S Rank':              315,
    'Starfall: SS Rank':             316,
    'Balloon High: E Rank':          320,
    'Balloon High: D Rank':          321,
    'Balloon High: C Rank':          322,
    'Balloon High: B Rank':          323,
    'Balloon High: A Rank':          324,
    'Balloon High: S Rank':          325,
    'Balloon High: SS Rank':         326,
    'Mermaid Cove: E Rank':          330,
    'Mermaid Cove: D Rank':          331,
    'Mermaid Cove: C Rank':          332,
    'Mermaid Cove: B Rank':          333,
    'Mermaid Cove: A Rank':          334,
    'Mermaid Cove: S Rank':          335,
    'Mermaid Cove: SS Rank':         336,
    'Orbit: E Rank':                 340,
    'Orbit: D Rank':                 341,
    'Orbit: C Rank':                 342,
    'Orbit: B Rank':                 343,
    'Orbit: A Rank':                 344,
    'Orbit: S Rank':                 345,
    'Orbit: SS Rank':                346,
    'Stratosphere: E Rank':          350,
    'Stratosphere: D Rank':          351,
    'Stratosphere: C Rank':          352,
    'Stratosphere: B Rank':          353,
    'Stratosphere: A Rank':          354,
    'Stratosphere: S Rank':          355,
    'Stratosphere: SS Rank':         356,
    'Metamorphosis: E Rank':         360,
    'Metamorphosis: D Rank':         361,
    'Metamorphosis: C Rank':         362,
    'Metamorphosis: B Rank':         363,
    'Metamorphosis: A Rank':         364,
    'Metamorphosis: S Rank':         365,
    'Metamorphosis: SS Rank':        366,
}

effect_ranksanity_locations = {
    'Marathon: E Rank':              370,
    'Marathon: D Rank':              371,
    'Marathon: C Rank':              372,
    'Marathon: B Rank':              373,
    'Marathon: A Rank':              374,
    'Marathon: S Rank':              375,
    'Marathon: SS Rank':             376,
    'Zone Marathon: E Rank':         380,
    'Zone Marathon: D Rank':         381,
    'Zone Marathon: C Rank':         382,
    'Zone Marathon: B Rank':         383,
    'Zone Marathon: A Rank':         384,
    'Zone Marathon: S Rank':         385,
    'Zone Marathon: SS Rank':        386,
    'Ultra: E Rank':                 390,
    'Ultra: D Rank':                 391,
    'Ultra: C Rank':                 392,
    'Ultra: B Rank':                 393,
    'Ultra: A Rank':                 394,
    'Ultra: S Rank':                 395,
    'Ultra: SS Rank':                396,
    'Sprint: E Rank':                400,
    'Sprint: D Rank':                401,
    'Sprint: C Rank':                402,
    'Sprint: B Rank':                403,
    'Sprint: A Rank':                404,
    'Sprint: S Rank':                405,
    'Sprint: SS Rank':               406,
    'Master: E Rank':                410,
    'Master: D Rank':                411,
    'Master: C Rank':                412,
    'Master: B Rank':                413,
    'Master: A Rank':                414,
    'Master: S Rank':                415,
    'Master: SS Rank':               416,
    'Classic Score Attack: E Rank':  420,
    'Classic Score Attack: D Rank':  421,
    'Classic Score Attack: C Rank':  422,
    'Classic Score Attack: B Rank':  423,
    'Classic Score Attack: A Rank':  424,
    'Classic Score Attack: S Rank':  425,
    'Classic Score Attack: SS Rank': 426,
    'Chill Marathon: E Rank':        430,
    'Chill Marathon: D Rank':        431,
    'Chill Marathon: C Rank':        432,
    'Chill Marathon: B Rank':        433,
    'Chill Marathon: A Rank':        434,
    'Chill Marathon: S Rank':        435,
    'Chill Marathon: SS Rank':       436,
    'Quick Play: E Rank':            440,
    'Quick Play: D Rank':            441,
    'Quick Play: C Rank':            442,
    'Quick Play: B Rank':            443,
    'Quick Play: A Rank':            444,
    'Quick Play: S Rank':            445,
    'Quick Play: SS Rank':           446,
    'Playlist (Sea): E Rank':        450,
    'Playlist (Sea): D Rank':        451,
    'Playlist (Sea): C Rank':        452,
    'Playlist (Sea): B Rank':        453,
    'Playlist (Sea): A Rank':        454,
    'Playlist (Sea): S Rank':        455,
    'Playlist (Sea): SS Rank':       456,
    'Playlist (Wind): E Rank':       460,
    'Playlist (Wind): D Rank':       461,
    'Playlist (Wind): C Rank':       462,
    'Playlist (Wind): B Rank':       463,
    'Playlist (Wind): A Rank':       464,
    'Playlist (Wind): S Rank':       465,
    'Playlist (Wind): SS Rank':      466,
    'Playlist (World): E Rank':      470,
    'Playlist (World): D Rank':      471,
    'Playlist (World): C Rank':      472,
    'Playlist (World): B Rank':      473,
    'Playlist (World): A Rank':      474,
    'Playlist (World): S Rank':      475,
    'Playlist (World): SS Rank':     476,
    'All Clear: E Rank':             480,
    'All Clear: D Rank':             481,
    'All Clear: C Rank':             482,
    'All Clear: B Rank':             483,
    'All Clear: A Rank':             484,
    'All Clear: S Rank':             485,
    'All Clear: SS Rank':            486,
    'Combo: E Rank':                 490,
    'Combo: D Rank':                 491,
    'Combo: C Rank':                 492,
    'Combo: B Rank':                 493,
    'Combo: A Rank':                 494,
    'Combo: S Rank':                 495,
    'Combo: SS Rank':                496,
    'Target: E Rank':                500,
    'Target: D Rank':                501,
    'Target: C Rank':                502,
    'Target: B Rank':                503,
    'Target: A Rank':                504,
    'Target: S Rank':                505,
    'Target: SS Rank':               506,
    'Countdown: E Rank':             510,
    'Countdown: D Rank':             511,
    'Countdown: C Rank':             512,
    'Countdown: B Rank':             513,
    'Countdown: A Rank':             514,
    'Countdown: S Rank':             515,
    'Countdown: SS Rank':            516,
    'Purity: E Rank':                520,
    'Purity: D Rank':                521,
    'Purity: C Rank':                522,
    'Purity: B Rank':                523,
    'Purity: A Rank':                524,
    'Purity: S Rank':                525,
    'Purity: SS Rank':               526,
    'Mystery: E Rank':               530,
    'Mystery: D Rank':               531,
    'Mystery: C Rank':               532,
    'Mystery: B Rank':               533,
    'Mystery: A Rank':               534,
    'Mystery: S Rank':               535,
    'Mystery: SS Rank':              536,
}

